DBO/Controllers/CompaniesController.cs
using DBO.Common;
using DBO.Data;
using DBO.Data.Models;
using DBO.Data.Repositories;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DBO.Controllers
{
    [Authorize(Roles = Constants.AdminRole)]
    public class CompaniesController : BaseController
    {
        private ApplicationDbContext db;
        private readonly CompanyRepository _companyRepository;
        private readonly UserRepository _userRepository;

        public CompaniesController()
        {
            db = new ApplicationDbContext();
            _companyRepository = new CompanyRepository();
            _userRepository = new UserRepository();
        }

        // GET: Companies
        public ActionResult Index(string search)
        {
            ViewBag.Search = search;
            var companies = db.Companies.AsEnumerable();
            if (!string.IsNullOrEmpty(search))
            {
                companies = companies.Where(c => c.Name.ToLower().Contains(search.ToLower()));
            }

            return View(companies.Take(100).ToList());
        }

        // GET: Companies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }

            var skills = db.CompanySkills.Include(s => s.Skill).Where(s => s.CompanyId == id);
            company.CompanySkills = skills.ToList();

            return View(company);
        }

        // GET: Companies/Admin/5
        public ActionResult Admin(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }

            var skills = db.CompanySkills.Include(s => s.Skill).Where(s => s.CompanyId == id);
            company.CompanySkills = skills.ToList();

            return View(company);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,PostCode,Image,Address,City,Phone,TextDescription,Connections")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Companies.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(company);
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,PostCode,Image,Address,City,Phone,TextDescription,Connections")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Company company = db.Companies.Find(id);
            db.Companies.Remove(company);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Employments()
        {
            var employees = _userRepository.GetUsersByRole(Constants.EmployeeRole);
            return View(employees);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UpdateEmployment(string username, int? companies)
        {
            if(string.IsNullOrEmpty(username))
            {
                return View("Error");
            }

            var user = await _userRepository.FindAsync(username);
            user.CompanyId = companies;

            await _userRepository.SaveAsync();
            return RedirectToAction("Employments");
        }

        public ActionResult CompanySelect2(int pageSize, int page, string term)
        {
            var model = _companyRepository.GetSelect2(pageSize, page, term);
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DBO/Views/Companies/Create.cshtml
@model DBO.Data.Models.Company
@{
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Resources.Company</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TextDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TextDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TextDescription, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
                @Html.LabelFor(model => model.Connections, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Connections, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Connections, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Resources.Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink(Resources.BackToList, "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DBO/Views/Companies/Delete.cshtml
@model DBO.Data.Models.Company
@{
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}
<h3>@Resources.AreYouSureToDelete</h3>
<div>
    <h4>@Resources.Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TextDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TextDescription)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="@Resources.Delete" class="btn btn-default" /> |
            @Html.ActionLink(Resources.BackToList, "Index")
        </div>
    }
</div>

DBO/Views/Companies/Details.cshtml
@model DBO.Data.Models.Company
@{
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet">
<link href="~/Content/font-awesome.css" rel="stylesheet" />
<link href="~/Content/company-details.css" rel="stylesheet" />

<div class="container company-details">
    <div class="row">
        <div class="col-lg-3" style="padding:0; margin:0;">
        <div class="card-white" style="padding:15px;">
            <div class="company-logo">
                <img src="https://picsum.photos/300/100" />
            </div>
            <div class="skills">
                <div class="title-strikethrough">Skills</div>
                <ul>
                    @foreach (var skill in Model.CompanySkills)
                    {
                        <li>@skill.Skill.Name</li>
                    }
                </ul>
            </div>
            <hr />
            <div class="connections">
                <span>@Model.Connections</span>
                <p>Connections</p>
            </div>
            <div class="google-maps">
                <iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBWrd9XVWtqRwTdIh46sN4jsJUwGLElPxQ&q=@Model.Address" width="600" height="450" frameborder="0" style="border:0"></iframe>
            </div>
            <table class="contact">
                <tbody>
                    <tr>
                        <td valign="top">
                            <i class="fa fa-map-marker" aria-hidden="true"></i>
                        </td>
                        <td>
                            @Model.City<br />
                            @Model.Address<br />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
                        </td>
                        <td>
                            <div><a href="#">Link</a></div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <i class="fa fa-phone" aria-hidden="true"></i>
                        </td>
                        <td>
                            <div>@Model.Phone</div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <i class="fa fa-mobile-phone" style="margin-left:3px" aria-hidden="true"></i>
                        </td>
                        <td>
                            <div><a href="tel:@Model.Phone">Send til dim telefon</a></div>
                        </td>
                    </tr>
                </tbody>
            </table>
            </div>
            <div class="d-none">
                <a href="#"><img src="/img/google-1.png" alt=""></a>
            </div>
            <div class="d-none">
                <a href="#"><img src="/img/google-2.png" alt=""></a>
            </div>
            <div class="d-none">
                <a href="#"><img src="/img/google-3.png" alt=""></a>
            </div>
            
        </div>
        <div class="col-lg-6">
            <div class="card add-article" style="margin-bottom:20px;">
                <div class="card-header header">
                    Skriv til Esbjerg Erhvervsudvikling
                </div>
                <div class="card-block body">
                    <textarea placeholder="Skriv din besked her..." rows="2"></textarea>
                    <div class="col-md-12">
                        <span class="col-md-3" style="color:lightgray;">Indsæt billede</span>
                        <button class="btn btn-success pull-right" style="margin-bottom:10px;">SEND</button>
                    </div>
                </div>
            </div>
            <div class="company-article">
                <div class="card company-article-data">
                    <div class="card-block article-body">
                        <img src="https://picsum.photos/200/20" />
                        <h4 class="card-title">Ny erhvervschef</h4>
                        <p class="card-text ">
                            Ny erhvervschef En kompetent kapacitet bliver den nye erhvervschef i Esbjerg Erhvervsudvikling.
                            I et stærkt felt af ansøgere løb tidligere direktør for Rybners, Karsten Rieder
                            af med jobbet som erhvervschef i Esbjerg Erhvervsudvikling.
                        </p>
                        <div class="row article-footer">
                            <span class="views"> 12 visninger</span>
                            <span>4 kommentarer</span>
                        </div>
                    </div>

                </div>
                <div class="card  comment-form">
                    <div class="card-block">
                        <textarea placeholder="Skriv kommentar..." rows="1"></textarea>
                    </div>
                </div>
            </div>
            <div class="company-article">
                <div class="card company-article-data">
                    <div class="card-block article-body">
                        <img src="https://picsum.photos/300/50" />
                        <h4 class="card-title">Ny erhvervschef</h4>
                        <p class="card-text ">
                            Ny erhvervschef En kompetent kapacitet bliver den nye erhvervschef i Esbjerg Erhvervsudvikling.
                            I et stærkt felt af ansøgere løb tidligere direktør for Rybners, Karsten Rieder
                            af med jobbet som erhvervschef i Esbjerg Erhvervsudvikling.
                            <img src="https://picsum.photos/600/400" />
                        </p>
                        <div class="row article-footer">
                            <span class="views"> 12 visninger</span>
                            <span>4 kommentarer</span>
                        </div>
                    </div>

                </div>
                <div class="card  comment-form">
                    <div class="card-block">
                        <textarea placeholder="Skriv kommentar..." rows="1"></textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 card-white" style="min-height:710px;">
            <div class="add-connection">
                @*@Html.Action(AddConnection)*@
                <a href="#">+ Connection</a>
            </div>
            <div class="title-strikethrough">Connections</div>
            @* model connections loop*@
            <div class="connection-logo">
                <img src="~/img/img-1.png" />
            </div>
            <div class="connection-logo">
                <img src="~/img/img-2.png" />
            </div>
        </div>
    </div>
</div>


@section scripts{

}

DBO/Views/Companies/Edit.cshtml
@model DBO.Data.Models.Company
@{
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Resources.Company</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TextDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TextDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TextDescription, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink(Resources.BackToList, "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DBO/Views/Companies/Employments.cshtml
@model IEnumerable<DBO.Data.Models.ApplicationUser>

@{
    ViewBag.Title = "Employments";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<h2>Employments</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Company.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @if (item.Company != null)
                {
                    @Html.DisplayFor(modelItem => item.Company.Name)
                }
            </td>
            <td>
                @{ 
                    var companyId = item.Company == null ? -1 : item.Company.Id;
                    var companyName = item.Company == null ? "" : item.Company.Name;
                 }
                <a href="" onclick="openUpdateModal('@item.UserName', '@companyId', '@companyName'); return false;">Update employment</a>
            </td>
        </tr>
    }

</table>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            @using (Html.BeginForm("UpdateEmployment", "Companies", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="modal-header">

                    <h4 class="modal-title">Update Employment</h4>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label>Employee</label>
                        <div class="col-md-10">
                            <input type="text" readonly name="username" id="username" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Companies</label>
                        <div class="col-md-10">
                            <select id="companies-dropdown" name="companies" class="form-control"></select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Update</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            }
        </div>

    </div>
</div>

@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    <script>
        $(function () {
            $('#myModal').on('hidden.bs.modal', function () {
                $('#companies-dropdown').empty();
            });
            $('#companies-dropdown').on('select2:select', function (e) {
                var data = e.params.data;
                console.log(data);
            });
        });
        function openUpdateModal(username, companyId, companyName) {
            var nCompany = parseInt(companyId);
            if (nCompany > -1) {
                $('#companies-dropdown').append($("<option></option>").attr("value", nCompany).text(companyName)); 
            }

            $('#companies-dropdown').select2({
                minimumInputLength: 0,
                allowClear: true,
                width: '100%',
                placeholder: 'Company name',
                ajax: {
                    url: '@Url.Action("CompanySelect2", "Companies")',
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        var req = {
                            pageSize: 20,
                            page: params.page ? params.page : 1,
                            term: params.term ? params.term : '',
                        };

                        return req;
                    },
                    processResults: function (data, params) {
                        var page = params.page ? params.page : 1;
                        var more = (page * 20) < data.TotalCount;
                        return {
                            results: data.Items,
                            pagination: {
                                more: more
                            }
                        };
                    },
                    cache: true,
                }
            });

            $('#username').val(username);
            $('#myModal').modal('show');
        }
    </script>
}

DBO/Views/Companies/Index.cshtml
@model IEnumerable<DBO.Data.Models.Company>
@{
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}
<div class="col-md-6">
    @Html.ActionLink(Resources.CreateNew, "Create")
</div>
<div class="col-md-6">
    <form>
        <div class="form-row">
            <div class="form-group col">
                <input type="text" class="form-control" name="search" placeholder="" value="@ViewBag.Search">
            </div>
            <div class="form-group col-auto">
                <input type="submit" class="btn btn-dark btn-block" value="@Resources.Search" />
            </div>
        </div>
    </form>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Connections)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Connections)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>